name: Test, build and publish module CI

on:
   push:
      branches: ['main']
   pull_request:
      branches: ['main']

jobs:
   build:
      runs-on: ubuntu-latest
      permissions:
         contents: read
         packages: write
      steps:
         - uses: actions/checkout@v3
         - uses: oven-sh/setup-bun@v1
         - name: bun install, and build
           run: |
              bun install
              bun run build

         - uses: actions/setup-node@v3
           with:
              node-version: 16
              registry-url: 'https://registry.npmjs.org'
         - name: Publish on NPM
           run: npm publish --access public
           env:
              NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
